/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opencvandroid_MainActivity */

#ifndef _Included_com_example_opencvandroid_MainActivity
#define _Included_com_example_opencvandroid_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_opencvandroid_MainActivity_CAMERA_PERMISSION_REQUEST_CODE
#define com_example_opencvandroid_MainActivity_CAMERA_PERMISSION_REQUEST_CODE 200L
/*
 * Class:     com_example_opencvandroid_MainActivity
 * Method:    DetectNumber
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_opencvandroid_MainActivity_DetectNumber
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_example_opencvandroid_MainActivity
 * Method:    loadCascade
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_opencvandroid_MainActivity_loadCascade
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
